### ISSUE TITLE
Bug: Component gets rerendered when trying to transition to impossible state

### ISSUE THREAD

**Issue by kirillku** [MicheleBertoli/react-automata#61]
First of all, thanks for a great lib. I started to use `react-automata` in my project and found one issue. When there is an transition to impossible state, the transition doesn't happen, but component still gets rerendered. As for me, in this case nothing should happen. I checked the code, looks like you do `setState` on wrapper component even if a transition was not possible and this results in rerendering wrapped component.

Here is a codesandbox with example: https://codesandbox.io/s/9lz8jq68ro

**Comment by MicheleBertoli** [comment]
Thank you very much for opening this issue, @kirillku.

I confirm that, at the moment, `react-automata` is setting the state on each `transition` call (even when the machine state is not changed).
I'm planning to implement a few optimisations soon.

However, this shouldn't be an issue as your components should be able to render multiple times with no side-effects.
In any case, if you want to prevent the component to re-render when the state doesn't change, you can extends `PureComponent` (instead of `Component`).

I hope this helps.

**Comment by MicheleBertoli** [comment]
Hey @kirillku, [v4](https://github.com/MicheleBertoli/react-automata/releases/tag/v4.0.0) is out and now the component renders only when the machine state actually changes.

<img width="420" alt="screen shot 2018-08-09 at 3 35 52 pm" src="https://user-images.githubusercontent.com/1308971/43902290-f9886198-9be9-11e8-84ba-d0a87494a34c.png">
