### ISSUE TITLE
Action methods are not receiving extState/event objects

### ISSUE THREAD

**Issue by brianlawasdf123** [MicheleBertoli/react-automata#63]
xstate shows an example of action methods receiving arguments `extState, event` http://davidkpiano.github.io/xstate/docs/#/api/actions?id=transitionactions

However, Component action methods don't seem to be receiving these arguments. Could they be added?
https://github.com/MicheleBertoli/react-automata/blob/master/src/withStatechart.js#L78

Heres an example: https://codesandbox.io/s/0q7r7po9np

**Comment by MicheleBertoli** [comment]
Thank you very much for opening this issue @brianlawasdf123.

At the moment, actions don't receive any parameter because you can access those information through props or lifecycle hooks, but in the new version of this library that I'm currently writing I added the parameters to keep consistency with `xstate`.

Stay tuned!

**Comment by MicheleBertoli** [comment]
Hey @brianlawasdf123, [v4](https://github.com/MicheleBertoli/react-automata/releases/tag/v4.0.0) is out and now actions receive arguments.

<img width="437" alt="screen shot 2018-08-09 at 3 34 04 pm" src="https://user-images.githubusercontent.com/1308971/43902185-b76abc48-9be9-11e8-83c9-d3d4c02a7561.png">

**Comment by brianlawasdf123** [comment]
Awesome! Thanks.
