### ISSUE TITLE
Inconsistent lifecycle methods firing

### ISSUE THREAD

**Issue by tastywheat** [MicheleBertoli/react-automata#66]
I'm seeing the `componentDidTransition` inconsistently firing.

Reproduce:
1. Go to https://codesandbox.io/s/30x3r5vj6p, and open console
2. Click **dowork** button. Notice `willTransition`, `beep` action, and `didTransition` fires as expected
3. Click **dowork** again. Notice `willTransition` and `didTransition` fires
4. Click **dowork** again (one or more times). Notice only `willTransition` fires

Expectation:
I expect steps 3 and 4 to be firing the same lifecycle methods consistently. I'm not sure if they should fire both `willTransition` and `didTransition` or only `willTransition`.

**Comment by MicheleBertoli** [comment]
Hello @tastywheat, thank you very much for opening a complete issue with a non-working example, repro steps and expectation.

I confirm there was a subtle bug in v4 that was causing `didTransition` to fire more than needed - which is now fixed in v.4.0.1.

It's correct when you say that 3 and 4 should fire the same hooks, and the expected behaviour is that `willTransition` fires every time the `transition` function is called, while `didTransition` only when a transition actually happens (which isn't the case in you Sandbox).

This is now the output:

<img width="322" alt="screen shot 2018-08-12 at 9 24 36 am" src="https://user-images.githubusercontent.com/1308971/43999678-9687c4d8-9e11-11e8-8149-d58f73df66e1.png">
